### PR TITLE
Coding style updates

### PR DESCRIPTION
**Pull request by paladox**
I manually did the update with out any software telling me where errors were.

So if you run php code sniffer there may be more warnings but I fixed the spaces and curly braces.

### CODE REVIEW

**Comment by PhrozenByte** [comment]
You want to change from PSR-0 to PSR-4 autoloaders (#263), but don't want to follow PSR-1 and PSR-2 code styling? What's the advantage of another non-standard code styling? Your proposal is neither better nor worse oyejorges code styling, except for the fact that this is oyejorges project and he's the only person entitled to choose the code styling he *personally* prefers :wink:

**Comment by paladox** [comment]
Hi I carnt find anything on psr-1 or psr-2 I can only see psr-4 and psr-0 in google search results.

**Comment by PhrozenByte** [comment]
http://www.php-fig.org/psr/psr-1/
http://www.php-fig.org/psr/psr-2/

Code styling is a completely subjective thing, before doing this you should wait for @oyejorge's feedback if he actually wants this.

**Comment by paladox** [comment]
Well the closest thing to psr-0 is psr-4

Please see http://www.php-fig.org/psr/psr-0/ which recommends using psr-4.

**Comment by PhrozenByte** [comment]
You're probably mixing this up with #263 :smile:
PSR-0 and PSR-4 are about autoloading (your PR #263), PSR-1 and PSR-2 about code styling (this PR). I'm not talking about autoloading, I'm talking about this PR (code styling).

**Comment by paladox** [comment]
Oh. So psr-1 and psr-2 are code styling didn't know that sorry. I am not sure what to do to follow that. Is there any composer packages that follow there coding standards.

**Comment by PhrozenByte** [comment]
Exactly. Just read the PSR-1 and PSR-2 docs, they already contain examples. As said, before doing this you should wait for @oyejorge's feedback.

**Pull request merged**
