### PR TITLE
Set sensible permissions on library source files

### PR DESCRIPTION
**Pull request by atdt**
Files which are not meant to be directly invoked should not be marked
executable. This issue was flagged by the Debian packaging tool lintian
when preparing a Debian package of MediaWiki, which now bundles this library.

See https://phabricator.wikimedia.org/T113112.

### CODE REVIEW

**Comment by oyejorge** [comment]
Thanks!

**Comment by atdt** [comment]
@oyejorge Thanks you! Could you possibly cut a new release with this change?

**Comment by oyejorge** [comment]
Will do

**Comment by atdt** [comment]
@oyejorge, thanks very much! You may be pleased to know that your library is now a dependency for MediaWiki, and that it is used to power Wikipedia. See https://en.wikipedia.org/wiki/Special:Version#mw-version-libraries.

**Comment by oyejorge** [comment]
That's pretty cool, thanks for letting me know!

**Pull request merged**
