### PR TITLE
Performance improvements (+4% to speed in Magento2)

### PR DESCRIPTION
**Pull request by andrey-legayev**
Hi,

I've run xdebug profiler for Magento2 static content deploy and found huge amount of calls to in_array()
I've tried to optimize it and got ~4% performance improvement.

Pls review my changes.

Andrey

### CODE REVIEW

**Comment by andrey-legayev** [comment]
It looks like travis config is outdated... PHP versions are not supported anymore

**Comment by andrey-legayev** [comment]
Travis conf updated. All unite tests are passed.

**Comment by hostep** [comment]
@andrey-legayev: great job!

However, Magento2 is no longer going to use this original `less.php` library, they'll be moving to a different fork: https://github.com/wikimedia/less.php/ in Magento 2.3.3 and higher (see https://github.com/magento/magento2/commit/9a4332cb18945772c1458d53cd1a9c191c3f7a10).
That last one is better maintained then this original fork and has support for PHP 7.3 which Magento 2.3.3 needs.

So you'd best also send the same PR to the wikimedia fork :)

**Comment by andrey-legayev** [comment]
Thanks, I'll check it out

**Comment by andrey-legayev** [comment]
Submitted to Wikimedia fork: https://github.com/wikimedia/less.php/pull/14

**Pull request closed without merging**
