### PR TITLE
fix override mbstring.internal_encoding

### PR DESCRIPTION
**Pull request by pafnuty**
Test case:
```
mbstring.internal_encoding = UTF-8
mbstring.func_overload = 2 (or 4 or 7)
```
If i use `@import`
```
// main file contains:
@import "00-variables"; // in this file contains cyrillic text
@import "01-mixins";
@import "02-grid";
```
For clarity, the screenshots of what I found out during the long process of digging in the code.
Numbers indicate the anticipated order of outputting debug text.
Parse.php:
wdomainslessphp loclocalcncompilerlessparser php lessphp loc - sublime text
Output:
lessphp loc opera

Thus, only the first (main) file is processed correctly encoded, and the other is encoded, the default on the server

### CODE REVIEW

**Comment by pafnuty** [comment]
@oyejorge  I'm sorry, but don't quite understand why Scrutinizer gives an error

**Comment by oyejorge** [comment]
Looks like the configuration had an invalid setting that was no longer tolerated. Fixed it, but [Scrutinizer give's this](https://scrutinizer-ci.com/g/oyejorge/less.php/inspections/3909be55-320b-434f-bd0c-61f51b04e755/issues/files/lib/Less/Parser.php?status=new&orderField=path&order=asc):

> The property $mb_internal_encoding was declared of type boolean, but 
> ini_get('mbstring.internal_encoding') is of type string. Maybe add a type cast?

**Comment by pafnuty** [comment]
@oyejorge I hope I did the right thing to repair. All the same, I have very little experience in programming :baby_symbol:

**Comment by oyejorge** [comment]
Thanks!

**Pull request merged**
