### PR TITLE
Test phpunit through composer.json

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
Thanks.

**Comment by duzun** [comment]
How is it better to run phpunit over composer?
The recomended method in docs is to download and use the PHAR file.

**Comment by paladox** [comment]
Well phpunit wasent being run at all through travis ci. this way it is being tested.

**Comment by duzun** [comment]
But you don't have to include it through composer.

Take a look at one of my projects: [hQuery.php](https://travis-ci.org/duzun/hQuery.php)

All I have in the [.travis.yml](https://github.com/duzun/hQuery.php/blob/master/.travis.yml) file is this line:

```yml
script: phpunit tests/
```

**Comment by duzun** [comment]
Actually travis-ci has the proper version of phpunit for each PHP version preinstalled. You just call `phpunit` and no need to install it!

**Comment by paladox** [comment]
Well yes but not an up to date version of phpunit for example maybe for php 5.5 it would be phpuniut 4.x or 5.x for 5.4 its 4.5 and 4.5

**Pull request merged**
