### PR TITLE
Adrianbadarau issue 258 fix

### PR DESCRIPTION
**Pull request by adrianbadarau**
A quick fix for issue #258 

Not complete but it's a start

### CODE REVIEW

**Comment by Asenar** [comment]
Hi @adrianbadarau why do you write it's not complete ?

**Comment by Asenar** [comment]
Hi @adrianbadarau , I wanted this feature, thanks you !

After some tests, it seems what missing is to parse all `@import` rules too, right ?

**Comment by Asenar** [comment]
Hi @adrianbadarau , I wanted this feature, thanks you !

I modified a small part of your code and it seems it's working (at least when parsing `variables.less` from twitter-bootstrap.

I took your changes to rebase them on the current master :)  https://github.com/Asenar/less.php

**Comment by adrianbadarau** [comment]
Project abbandoned

**Pull request closed without merging**
